#修改7002主机yml文件
server:
  port: 7002
eureka:
  instance:
    # eureka服务端的实例名字
    hostname: eureka7002.com
  client:
    #表 示是否将自己注册到Eureka Server
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册的服务信息
    fetch-registry: false
    # 设置与 Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
