server:
  port: 80
eureka:
  client:
    service-url:
      # Eureka server 地址
      defaultZone: http://localhost:7001/eureka/
  instance:
    #根据需要自己起名字
    instance-id: cloud-order-consumer-80

spring:
  application:
    # 设置应用名字
    name: cloud-order-consumer

